name: Rodrigo Machado Blog
description: Random thoughts of a random web developer
meta_description: "Blog about web development and related stuff"

aboutPage: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Default GitHub config
lsi: false
# safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

paginate: 20
baseurl: /
domain_name: 'http://machado.io'
google_analytics: 'UA-10254127-3'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://machado.io'
author:         'Rodrigo Machado'
authorTwitter:  'rcmachado'

permalink:       /:year/:title/

gems: ['jekyll-paginate']

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
